# Generated by Django 2.1.4 on 2019-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('sex', models.IntegerField(default=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
