# Generated by Django 2.1.4 on 2019-08-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_project_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='avalible',
            field=models.IntegerField(choices=[(0, '无效'), (1, '有效')], default=1),
        ),
    ]
