# Generated by Django 2.1.4 on 2019-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_task_avalible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('headers', models.TextField(null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('body', models.TextField(null=True)),
                ('checks', models.CharField(max_length=200)),
            ],
        ),
    ]
